name: sp500-prediction-env
channels:
  - conda-forge
dependencies:

  # The Works
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - ipykernel

  # Parallel Computing
  - dask

  # Web Scraping
  - beautifulsoup4
  - requests
  - grequests

  # Finance Data
  - yfinance
  - alpha_vantage

  # Machine Learning
  - tensorflow
  - scikit-learn

  # Secrets
  - python-dotenv

  # LLMs / NLP
  - openai
  - tiktoken
  - nltk

  # Other
  - pyarrow
  - tqdm
  - ipywidgets
  - jinja2
  - pip
  - pip:
    - stockstats
    - pylcs